const STATICS = {
  NAVBAR_TITLE: "E-COMM",
  HOME: "HOME",
  ELECTRONICS: "ELECTRONICS",
  BOOKS: "BOOKS",
  MUSIC: "MUSIC",
  MOVIES: "MOVIES",
  CLOTHING: "CLOTHING",
  GAMES: "GAMES",
  MORE: "MORE",
  FURNITURE: "FURNITURE",
  TRAVEL: "TRAVEL",
  BOTANICAL: "BOTANICAL",
  NAVBAR_SEARCH_PLACEHOLDER: "Search something",
  FEATURED_PRODUCT: "Featured Product",
  EXPLORE_AND_DISCOVER: "Explore and discover a variety of products",
  SERENE_LANDSCAPES: "Serene Landscapes",
  SHINY_BEACHES: "Shiny Beaches",
  WATERFALL_BLISS: "Waterfall Bliss",
  ROCKY_SHORES: "Rocky Shores",
  MESMERIZING_MOUNTAINS: "Mesmerizing mountains",
  INFINITE_CAROUSEL_TYPE: "Infinite",
  FINITE_CAROUSEL_TYPE: "Finite",
};

export default STATICS;
